services:
  api1: &api
    image: api
    hostname: api1
    environment:
      RAILS_ENV: production
      WEB_CONCURRENCY: 3
      RAILS_MAX_THREADS: 6
      RUBY_YJIT_ENABLE: 1
    expose:
      - "5000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "205MB"
  api2:
    <<: *api
    hostname: api2
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "35MB"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "api_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "105MB"

volumes:
  postgres:

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1