services:
  api1:
    image: api
    hostname: api1
    expose:
      - "5000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
  api2:
    image: api
    hostname: api2
    expose:
      - "5000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "api_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"

volumes:
  mysql: