default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: "api_db"
  username: "user"
  password: "password"
  port: 5432
  host: "db"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
