default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: "api_db"
  username: "user"
  password: "password"
  port: 3306
  host: "db"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
