default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  database: "api_db"
  username: "user"
  password: "password"
  port: 5432
  host: "db"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
